---

#
#
# we need to disable all non os repos
- name: "{{ target_hosts|upper }} - Update the operating system"
  yum:
    name: "*"
    update_cache: yes
    state: latest
    disablerepo: "{{ disable_repos }}"

