---

- hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  serial: "{{ parallel_host|default(1)|int }}"
  vars:
    - service: "{{ target_service }}"
    - update_os: "{{ update_os|default(true)|bool"
    - update_app: "{{ update_app|default(true)|bool"
  roles:
   - role: load_config

   #- role: email_nofification
   #  vars:
   #    - notify_step: "start"
   #  when: notify_operation == true
      
   - role: start_services

   - role: api_check
     vars:
      - plugin_api: "{{ api_plugin_start }}"
      - es_retry: 10
      - es_delay: 30
     when: 
       - api_check|default(false)|bool == true
       - api_check_before_stop|default(false)|bool == true

   - role: stop_services

   - role: update_os
     when: update_os|default(false)|bool == true

   - role: update_app
     vars:
       - plugin_app:
           - plugin_elk_installer.yml 
     when: update_app|default(false)|bool == true

   - role: reboot_server
     when: 
       - reboot_after_os_update|default(false)|bool == true
       - update_os|default(false)|bool == true

   - role: start_services

   - role: check_process
     when: 
       - check_process == true
       - break_exec|default(false)|bool == false

   - role: check_ports
     when: 
       - check_ports == true
       - break_exec|default(false)|bool == false


   - role: api_check
     vars:
       - plugin_api: "{{ api_plugin_end }}"
       - es_retry: 10
       - es_delay: 30
     when: 
       - api_check|default(false)|bool == true
       - api_check_after_stop|default(false)|bool == true
       - break_exec|default(false)|bool == false
       
   #
   # Send email if needed when the execution is success
   - role: email_nofification
     vars:
       - notify_step: "end"
       - notify_if: "success" # error, success
     when: 
       - notify_operation|default(false)|bool == true
       - notify_on_success|default(false)|bool == true
       - exec_is_success|default(false)|bool == true
       #- break_exec|default(false)|bool == false

   #
   # Send email if needed when the execution is failed
   - role: email_nofification
     vars:
       - notify_step: "end"
       - notify_if: "error" # error, success
     when: 
       - notify_operation|default(false)|bool == true
       - notify_on_failure|default(false)|bool == true
       - exec_is_success|default(false)|bool == false
       #- break_exec|default(false)|bool == true

   #
   # Create tasks if needed when the execution is success
   - role: create_jira
     vars:
       - create_jira: "task"
     when: 
       - create_jira|default(false)|bool == true
       - create_jira_on_success|default(false)|bool == true
       - exec_is_success|default(false)|bool == true
       #- break_exec|default(false)|bool == false

   #
   # Create issue if needed when the execution is failed
   - role: create_jira
     vars:
       - create_jira: "issue"
     when: 
       - create_jira|default(false)|bool == true
       - create_jira_on_failure|default(false)|bool == true
       - exec_is_success|default(false)|bool == false
       #- break_exec|default(false)|bool == true

   #
   # Break the execution
   - role: break_execution
     when: on_failure_break_execution|default(false)|bool == true


