---

- hosts: "{{ target_hosts }}"
  become: yes
  gather_facts: no
  serial: "{{ parallel_host|default(1)|int }}"
  vars:
    - service: "{{ target_service }}"
    - update_os: "{{ update_os|default(true)|bool"
    - update_app: "{{ update_app|default(true)|bool"
  roles:
   - role: load_config

   #- role: email_nofification
   #  vars:
   #    - notify_step: "start"
   #  when: notify_start_operation == true
      
   - role: start_services

   - role: api_check
     vars:
      - plugin_api: "{{ api_plugin_start }}"
      - es_retry: 10
      - es_delay: 30
     when: 
       - api_check|default(false)|bool == true
       - api_check_before_stop|default(false)|bool == true

   - role: stop_services

   - role: update_os
     when: update_os|default(false)|bool == true

   - role: update_app
     vars:
       - plugin_app:
           - plugin_elk_installer.yml 
     when: update_app|default(false)|bool == true

   - role: reboot_server
     when: 
       - reboot_after_os_update|default(false)|bool == true
       - update_os|default(false)|bool == true

   - role: start_services

   - role: check_process
     when: check_process == true

   - role: check_ports
     when: check_ports == true


   - role: api_check
     vars:
      - plugin_api: "{{ api_plugin_end }}"
      - es_retry: 10
      - es_delay: 30
     when: 
       - api_check|default(false)|bool == true
       - api_check_after_stop|default(false)|bool == true
       

   - role: email_nofification
     vars:
       - notify_step: "end"
       - notify_if: "all" # error, success, all, both
     when: notify_start_operation|default(false)|bool == true

   - role: create_jira
     vars:
       - create_jira_if: "all" # error, success, all, both
       - create_jira_on_success: "task"
       - create_jira_on_error: "issue"
     when: create_jira|default(false)|bool == true

#- include: playbooks/update/main.yml target_hosts='elasticsearch' service='elk'

#- include: playbooks/update/main.yml target_hosts='kibana' service='elk'

#- include: playbooks/update/main.yml target_hosts='logstash' service='elk'

#- include: playbooks/update/main.yml target_hosts='beats' service='elk' parallel_host=5
