---


- name: "{{ target_hosts|upper }} - Enable shard allocation for the cluster"
  uri: 
    url: "{{ es_proto }}://{{ inventory_hostname }}:{{ es_http_port }}/_cluster/settings" 
    method: PUT 
    body: "{{ es_enable_allocation }}"
    body_format: json
    user: "{{es_api_basic_auth_username|default(omit)}}"
    password: "{{es_api_basic_auth_password|default(omit)}}"
    return_content: yes
    force_basic_auth: "{{ es_force_auth|default(no)|bool }}"
  register: response
  until: "response.json.acknowledged == true"
  retries: "{{es_retry|default(10)|int}}"
  delay: "{{es_retry|default(30)|int}}"
  #when: version_found.json.version.number != '{{ es_version }}'


- debug:
    var: response
  when: activate_debug|default(false)|bool == true
