---

#
#
# Email notification
- name: Sending an e-mail for notification
  mail:
    host: smtp.gmail.com
    port: 465 #587
    username: xenos.psy@gmail.com
    password: Psycho_1984
    to: amine.tamdy@gmail.com
    subject: "{{ current_host }} {{ notify_if }} to start service {{ target }}"
    body: "System {{ current_host }} has {{ notify_if }} to start service. {{ service }}"
    secure: always
  ignore_errors: yes
  delegate_to: localhost

#
#
- debug:
    msg: "{{ current_host }} - {{ service }} - {{ target }}"
  when: activate_debug|default(false)|bool == true
    
